---
apiVersion: v1
kind: Service
metadata:
  name: parking-svc
  namespace: exjnamespace
spec:
  type: NodePort
  selector:
    app: parking
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parking
  namespace: exjnamespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: parking
  template:
    metadata:
      labels:
        app: parking
    spec:
      containers:
      - name: parking-pod
        image: jpralves/parking-microservice:latest
        ports:
        - containerPort: 8080
        env:
          - name: NODE_ENV
            value: "funny"
          - name: POSTGRES_HOST
            value: postgres-svc