---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin4-svc
  namespace: exjnamespace
spec:
  type: NodePort
  selector:
    app: pgadmin4
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin4
  namespace: exjnamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin4
  template:
    metadata:
      labels:
        app: pgadmin4
    spec:
      containers:
      - name: pgadmin4-pod
        image: dpage/pgadmin4
        ports:
        - containerPort: 80
        env:
          - name: PGADMIN_DEFAULT_EMAIL
            value: "jpralves10@gmail.com"
          - name: PGADMIN_DEFAULT_PASSWORD
            value: "admin"