---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: exjnamespace
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - name: http
    protocol: TCP
    port: 5432
    targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: exjnamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres-pod
        image: postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: "Postgres2019!"
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}