---
apiVersion: v1
kind: Service
metadata:
  name: aplicacao-svc
spec:
  selector:
    type: frontend
  type: LoadBalancer
  ports:
    - name: http
      targetPort: 80
      port: 80
  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-dep
spec:
  template:
    metadata:
      name: aplicacao-pod
      labels:
        app: aplicacao
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 2
  selector:
    matchLabels:
      type: frontend