apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: aplicacao-rs
  labels:
    app: aplicacao
spec:
  template:
    metadata:
      name: aplicacao-pod
      labels:
        env: production
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 2
  selector:
    matchLabels:
      env: production