---
apiVersion: v1
kind: Service
metadata:
  name: adminer-svc
  namespace: exjnamespace
spec:
  type: NodePort
  selector:
    app: adminer
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: exjnamespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer-pod
        image: adminer
        ports:
        - containerPort: 8080