---
apiVersion: v1
kind: Service
metadata:
  name:  redis
  namespace: votacao
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
  - name: redis-service
    port: 6379
    targetPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radis
  namespace: votacao
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - name:  redis
          containerPort: 6379
        volumeMounts:
          - name:  redis-data
            mountPath: /data
      volumes:
        - name:  redis-data
          emptyDir: {}