---
apiVersion: v1
kind: Service
metadata:
  name:  result
  namespace: votacao
spec:
  selector:
    app: result
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  namespace: votacao
spec:
  replicas: 2
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: kodekloud/examplevotingapp_result:v1
        ports:
        - name: result
          containerPort: 80