---
apiVersion: v1
kind: Service
metadata:
  name:  votacao
  namespace: votacao
spec:
  selector:
    app: votacao
  type: NodePort
  ports:
  - port: 80
    targetPort: 80


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: votacao
  namespace: votacao
spec:
  replicas: 2
  selector:
    matchLabels:
      app: votacao
  template:
    metadata:
      labels:
        app: votacao
    spec:
      containers:
      - name: votacao
        image: kodekloud/examplevotingapp_vote:v1
        ports:
        - name: votacao
          containerPort: 80