apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: exjnamespace
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nfs:
    path: /data
    server: 127.0.0.1:2049