---
apiVersion: v1
kind: Service
metadata:
  name: exjtecnologia-svc
  namespace: exjnamespace
spec:
  type: NodePort
  selector:
    app: exjtecnologia
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exjtecnologia
  namespace: exjnamespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exjtecnologia
  template:
    metadata:
      labels:
        app: exjtecnologia
    spec:
      containers:
      - name: exjtecnologia-pod
        image: jpralves/exjtecnologia-k8s:latest
        ports:
        - containerPort: 8081
        env:
          - name: API_KEY
            value: "333"
        volumeMounts:
          - name:  env-vol
            mountPath: /env/exjtecnologia
          - name:  env-vol
            mountPath: /env/splunk
      volumes:
        - name:  env-vol
          emptyDir: {}