---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: exjnamespace
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
  - name: http
    protocol: TCP
    port: 9092
    targetPort: 9092

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: exjnamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka-pod
        image: docker.io/bitnami/kafka:2
        ports:
        - containerPort: 9092
        env:
          - name: KAFKA_CFG_LISTENERS
            value: PLAINTEXT://:9092
          - name: KAFKA_CFG_ADVERTISED_LISTENERS
            value: PLAINTEXT://127.0.0.1:9092
          - name: KAFKA_CFG_ZOOKEEPER_CONNECT
            value: zookeeper-svc:2181
          - name: ALLOW_PLAINTEXT_LISTENER
            value: "yes"
        volumeMounts:
          - name: kafka-data
            mountPath: /bitnami
      volumes:
        - name: kafka-data
          emptyDir: {}