---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-svc
  namespace: exjnamespace
spec:
  type: ClusterIP
  selector:
    app: zookeeper
  ports:
  - name: http
    protocol: TCP
    port: 2181
    targetPort: 2181

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: exjnamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper-pod
        image: docker.io/bitnami/zookeeper:3.7
        ports:
        - containerPort: 2181
        env:
          - name: ALLOW_ANONYMOUS_LOGIN
            value: "yes"
        volumeMounts:
          - name: zookeeper-data
            mountPath: /bitnami
      volumes:
        - name: zookeeper-data
          emptyDir: {}