---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: exjnamespace
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 8080


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-dp
  namespace: exjnamespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: kubedevio/api-produto:v1
        ports:
        - containerPort: 8080
        resources: {}
        env:
        - name: MONGODB_URI
          value: mongodb://mongouser:mongopwd@mongo-service:27017/admin