---
apiVersion: v1
kind: Service
metadata:
  name:  postgres
  namespace: votacao
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
  - name: postgres-service
    port: 5432
    targetPort: 5432

---    
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: votacao
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
        - name: POSTGRES_USER
          value: admin
        - name:  POSTGRES_PASSWORD
          value: admin
        ports:
        - name: postgres
          containerPort: 5432
        volumeMounts:
          - name:  postgres-data
            mountPath:  /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        emptyDir: {}
