---
apiVersion: v1
kind: Service
metadata:
  name:  result
  namespace: votacao
spec:
  selector:
    app: result
  type: NodePort
  ports:
  - name: result-service
    port: 5001
    targetPort: 80
    nodePort: 31001


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: result
  namespace: votacao
spec:
  replicas: 2
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: dockersamples/examplevotingapp_result:before
        ports:
        - name: result
          containerPort: 80