---
apiVersion: v1
kind: Service
metadata:
  name:  votacao
  namespace: votacao
spec:
  selector:
    app: votacao
  type: NodePort
  ports:
  - name: votacao-service
    port: 5000
    targetPort: 80
    nodePort: 31000


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: votacao
  namespace: votacao
spec:
  replicas: 2
  selector:
    matchLabels:
      app: votacao
  template:
    metadata:
      labels:
        app: votacao
    spec:
      containers:
      - name: votacao
        image: dockersamples/examplevotingapp_vote:before
        ports:
        - name: votacao
          containerPort: 80